# https://github.com/odin-lang/Odin/wiki/Compiler-Flags
[project]
name = "Ratatoskr"
version = "0.1.0"
authors = ["@Garkatron"]
path = "./src"
tests_path = "./tests"

[output]
development = "./out/dev-rtt-linux-amd64"
release = "./out/rtt-linux-amd64"
debug = "./out/debug-rtt-linux-amd64"

[collections]
libs = "./libs"

[compiler]
build_mode      = "exe"
debug           = false
ignore_warnings = false
disallow_do     = false

[compiler.defines]

[compiler.raw]
