name: Release Build

on:
    push:
        branches:
            - "**"

jobs:
    build:
        if: >
            github.ref == 'refs/heads/release' ||
            startsWith(github.event.head_commit.message, 'release:')
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Get Odin release tag
              id: odin-tag
              run: |
                  tag=$(curl -sL https://api.github.com/repos/odin-lang/Odin/releases/latest | grep '"tag_name"' | cut -d '"' -f4)
                  echo "tag=$tag" >> "$GITHUB_OUTPUT"

            - name: Cache Odin
              id: cache-odin
              uses: actions/cache@v4
              with:
                  path: odin-dist
                  key: odin-linux-amd64-${{ steps.odin-tag.outputs.tag }}

            - name: Download Odin
              if: steps.cache-odin.outputs.cache-hit != 'true'
              run: |
                  mkdir -p odin-dist
                  curl -L --fail -o odin.tar.gz \
                  https://github.com/odin-lang/Odin/releases/download/${{ steps.odin-tag.outputs.tag }}/odin-linux-amd64-${{ steps.odin-tag.outputs.tag }}.tar.gz
                  ls -la odin.tar.gz
                  tar -tzf odin.tar.gz > /dev/null
                  tar -xzf odin.tar.gz -C odin-dist --strip-components=1

            - name: Add Odin to PATH
              run: echo "$PWD/odin-dist" >> $GITHUB_PATH

            - name: Check toolchain
              run: |
                  which clang
                  clang --version
                  which ld.lld || echo "lld not found"

            - name: Install build tools
              run: sudo apt-get update && sudo apt-get install -y clang lld

            - name: Download rtt (release binary)
              run: |
                  curl -L -o rtt \
                  https://github.com/Garkatronics-Labs/Ratatoskr/releases/latest/download/rtt
                  chmod +x ./rtt

            - name: Build project with rtt
              run: |
                  mkdir -p out
                  ./rtt build --release

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rtt-build
                  path: out/

            - name: Generate release tag
              id: tag
              run: echo "tag=v$(date +%Y.%m.%d-%H%M)" >> "$GITHUB_OUTPUT"

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ steps.tag.outputs.tag }}
                  files: out/rtt
