name: Release Build

on:
    push:
        branches:
            - "**"

jobs:
    build:
        if: >
            github.ref == 'refs/heads/release' ||
            startsWith(github.event.head_commit.message, 'release:')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Download rtt (release binary)
              run: |
                  curl -L -o rtt \
                    https://github.com/Garkatronics-Labs/Ratatoskr/releases/download/v1.0.0/rtt
                  chmod +x ./rtt

            - name: Build project with rtt
              run: ./rtt build --release

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rtt-build
                  path: build/
